FROM node:10.10.0

RUN apt-get update && apt-get install -y \
    rsync

RUN echo 'PS1="\u@${POET_SERVICE:-noService}:\w# "' >> ~/.bashrc

WORKDIR /usr/src/app/api

COPY package*.json ./
RUN npm i --quiet
COPY . .
RUN npm run build
RUN npm run lint

CMD [ "npm", "run", "start:ci" ]
