import '../../src/middlewares/monitor.test'
import '../../src/middlewares/validate.test'
import '../../src/utils/Delay/Delay.test'
import '../../src/utils/Password/Password.test'
import '../../src/utils/Password/isPwned.test'
